// Generated by GPT-6, 2026-09-08. Pure MRU and switcher-session helpers.

const isTabId = (id) => Number.isInteger(id) && id >= 0;
const uniqueIds = (ids) => [...new Set((Array.isArray(ids) ? ids : []).filter(isTabId))];
const modulo = (index, length) => ((index % length) + length) % length;

/**
 * Reconcile saved MRU history with live tabs, separately for each window.
 * The active tab is always placed first, so call only on bootstrap/resync,
 * outside a selection session. Existing valid history keeps its relative order;
 * previously unknown tabs follow in descending lastAccessed order.
 */
export function reconcileHistory(historyByWindow = {}, tabs = []) {
  const windows = new Map();
  for (const tab of tabs) {
    if (!tab || !isTabId(tab.id) || !Number.isInteger(tab.windowId) || tab.windowId < 0) continue;
    const key = String(tab.windowId);
    if (!windows.has(key)) windows.set(key, new Map());
    windows.get(key).set(tab.id, tab);
  }

  const result = {};
  for (const [key, liveTabs] of windows) {
    const existing = uniqueIds(historyByWindow?.[key]).filter((id) => liveTabs.has(id));
    const known = new Set(existing);
    const unknown = [...liveTabs.values()]
      .filter((tab) => !known.has(tab.id))
      .sort((a, b) => (b.lastAccessed || 0) - (a.lastAccessed || 0));
    const ordered = [...existing, ...unknown.map((tab) => tab.id)];
    const active = [...liveTabs.values()].find((tab) => tab.active);
    result[key] = active ? [active.id, ...ordered.filter((id) => id !== active.id)] : ordered;
  }
  return result;
}

/** Return a new history with this activation most recent in its window. */
export function recordActivation(history = {}, windowId, tabId) {
  if (!Number.isInteger(windowId) || windowId < 0 || !isTabId(tabId)) return { ...history };
  const key = String(windowId);
  return { ...history, [key]: [tabId, ...uniqueIds(history[key]).filter((id) => id !== tabId)] };
}

/** Remove a closed/detached tab from every window without changing the input. */
export function removeTab(history = {}, tabId) {
  return Object.fromEntries(Object.entries(history).map(([key, ids]) => [
    key, uniqueIds(ids).filter((id) => id !== tabId),
  ]));
}

/**
 * Freeze one MRU snapshot for the entire switching gesture. Positive direction
 * starts on the previously visited tab; negative starts on the least recent.
 * The snapshot never reorders on highlight/activation, preventing ping-pong.
 */
export function createSelection(ids, direction = 1) {
  const snapshot = uniqueIds(ids);
  if (snapshot.length === 0) return null;
  return { ids: Object.freeze(snapshot), index: direction < 0 ? snapshot.length - 1 : 1 % snapshot.length };
}

/** Move through the original snapshot, wrapping in either direction. */
export function stepSelection(selection, direction = 1) {
  if (!selection?.ids?.length) return null;
  return { ids: selection.ids, index: modulo(selection.index + (direction < 0 ? -1 : 1), selection.ids.length) };
}

/** Keep the highlighted tab if possible; if closed, highlight its successor. */
export function removeFromSelection(selection, tabId) {
  if (!selection?.ids?.length) return null;
  const removedIndex = selection.ids.indexOf(tabId);
  if (removedIndex === -1) return { ids: selection.ids, index: selection.index };
  const ids = selection.ids.filter((id) => id !== tabId);
  if (ids.length === 0) return null;
  const highlighted = selectedId(selection);
  const retainedIndex = ids.indexOf(highlighted);
  return {
    ids: Object.freeze(ids),
    index: retainedIndex === -1 ? selection.index % ids.length : retainedIndex,
  };
}

export function selectedId(selection) {
  return selection?.ids?.[selection.index] ?? null;
}
