// Generated by GPT-6 Astra · Codex · 2026-09-08
const toggle = document.getElementById('toggle-previews');
const clear = document.getElementById('clear-previews');
const feedback = document.getElementById('feedback');
document.getElementById('version').textContent = `Recent Tabs · Version ${chrome.runtime.getManifest().version}`;
let enabled = false;
let busy = false;

async function send(message) {
  const result = await chrome.runtime.sendMessage(message);
  if (result?.ok === false) throw new Error(result.error || 'Could not save this setting.');
  return result;
}

function setBusy(value) {
  busy = value;
  toggle.disabled = value;
  clear.disabled = value;
}

function formatBytes(bytes) {
  return bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

async function refresh() {
  const result = await send({ type: 'get-settings' });
  const settings = result.settings || result;
  enabled = Boolean(settings.enabled);
  toggle.textContent = enabled ? 'Disable website previews' : 'Enable website previews';
  document.getElementById('preview-state').textContent = enabled ? 'Enabled' : 'Optional';
  document.getElementById('shortcut').textContent = settings.shortcut || 'Set shortcut';
  const count = Number(settings.cacheCount) || 0;
  const bytes = Number(settings.cacheBytes) || 0;
  document.getElementById('cache').textContent = `${count} saved ${count === 1 ? 'preview' : 'previews'} · ${formatBytes(bytes)} stored locally`;
  setBusy(false);
}

toggle.addEventListener('click', async () => {
  if (busy) return;
  setBusy(true);
  feedback.textContent = '';
  try {
    if (!enabled) {
      // Keep the permission request directly in this user gesture.
      const granted = await chrome.permissions.request({ origins: ['<all_urls>'] });
      if (!granted) {
        feedback.textContent = 'Previews stay off. Keyboard switching and title cards still work.';
        return;
      }
      await send({ type: 'set-previews', enabled: true });
      feedback.textContent = 'Previews enabled. Visit a few tabs to build your visual history.';
    } else {
      await send({ type: 'set-previews', enabled: false });
      await chrome.permissions.remove({ origins: ['<all_urls>'] });
      feedback.textContent = 'Previews disabled and saved screenshots cleared.';
    }
    await refresh();
  } catch (error) { feedback.textContent = error.message; }
  finally { setBusy(false); }
});

clear.addEventListener('click', async () => {
  if (busy) return;
  setBusy(true);
  try {
    await send({ type: 'clear-previews' });
    await refresh();
    feedback.textContent = 'Saved screenshots cleared.';
  } catch (error) { feedback.textContent = error.message; }
  finally { setBusy(false); }
});

document.getElementById('configure-shortcut').addEventListener('click', () => {
  chrome.tabs.create({ url: 'chrome://extensions/shortcuts' });
});

refresh().catch(error => {
  feedback.textContent = error.message;
  document.getElementById('preview-state').textContent = 'Unavailable';
});
