// Generated by GPT-6 Astra · Codex · 2026-09-08
// This isolated-world script never receives titles, URLs, or screenshot data.
(() => {
  if (globalThis.__arcRecentTabsOverlayInstalled) return;
  globalThis.__arcRecentTabsOverlayInstalled = true;
  let host = null;
  let frame = null;
  let sessionId = null;
  let previousFocus = null;
  let lastControlReleaseAt = 0;
  let controlHeld = null;
  const extensionOrigin = new URL(chrome.runtime.getURL('/')).origin;

  const send = message => {
    try { chrome.runtime.sendMessage(message)?.catch(() => {}); } catch { /* Extension was reloaded. */ }
  };
  const cleanup = () => {
    const restore = previousFocus;
    host?.remove();
    host = null;
    frame = null;
    sessionId = null;
    previousFocus = null;
    if (restore?.isConnected && typeof restore.focus === 'function') {
      try { restore.focus({ preventScroll: true }); } catch { /* Page changed. */ }
    }
  };
  const cancel = () => {
    if (!sessionId) return;
    send({ type: 'cancel', sessionId });
    cleanup();
  };

  // Register immediately, before loading the iframe, so fast releases are not lost.
  document.addEventListener('keydown', event => {
    if (!event.isTrusted) return;
    controlHeld = event.ctrlKey || event.key === 'Control';
    if (sessionId && event.key === 'Escape') {
      event.preventDefault();
      event.stopImmediatePropagation();
      cancel();
    }
  }, true);
  document.addEventListener('keyup', event => {
    if (!event.isTrusted) return;
    controlHeld = event.ctrlKey;
    if (event.key !== 'Control' || event.ctrlKey) return;
    lastControlReleaseAt = Date.now();
    send({ type: 'modifier-released', at: lastControlReleaseAt, ...(sessionId ? { sessionId } : {}) });
  }, true);
  document.addEventListener('visibilitychange', () => {
    if (document.hidden) cancel();
  });
  window.addEventListener('blur', () => {
    // Moving focus into our iframe fires parent blur; that is expected.
    setTimeout(() => {
      if (sessionId && !document.hasFocus()) cancel();
    }, 0);
  });
  window.addEventListener('pagehide', () => {
    if (sessionId) send({ type: 'ui-disconnected', sessionId });
  });
  window.addEventListener('message', event => {
    if (!frame || event.source !== frame.contentWindow || event.origin !== extensionOrigin) return;
    if (event.data?.type === 'arc-recent-tabs:close' && event.data.sessionId === sessionId) cleanup();
  });

  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (sender.id !== chrome.runtime.id) return;
    if (message.type === 'hide-overlay') {
      if (!message.sessionId || message.sessionId === sessionId) cleanup();
      sendResponse({ ok: true });
      return;
    }
    if (message.type !== 'show-overlay' || typeof message.sessionId !== 'string') return;
    if (host && sessionId === message.sessionId) {
      frame.focus({ preventScroll: true });
      sendResponse({ ok: true, releasedAt: lastControlReleaseAt, controlHeld });
      return;
    }
    cleanup();
    sessionId = message.sessionId;
    previousFocus = document.activeElement;
    host = document.createElement('div');
    host.setAttribute('data-arc-recent-tabs', '');
    host.style.cssText = 'all:initial!important;position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;z-index:2147483647!important;display:block!important;opacity:1!important;visibility:visible!important;pointer-events:auto!important;';
    const shadow = host.attachShadow({ mode: 'closed' });
    frame = document.createElement('iframe');
    frame.src = chrome.runtime.getURL('panel.html') + '?session=' + encodeURIComponent(sessionId);
    frame.title = 'Recent tabs';
    frame.style.cssText = 'display:block;width:100%;height:100%;border:0;background:transparent;color-scheme:dark;';
    frame.addEventListener('load', () => {
      if (!frame) return;
      frame.focus({ preventScroll: true });
      try { frame.contentWindow.focus(); } catch { /* Browser may restrict a focus request. */ }
    }, { once: true });
    shadow.append(frame);
    (document.documentElement || document.body).append(host);
    frame.focus({ preventScroll: true });
    sendResponse({ ok: true, releasedAt: lastControlReleaseAt, controlHeld });
  });
})();
