// Generated by GPT-6 Astra · Codex · 2026-09-08
const surface = document.body.dataset.surface;
const requestedSessionId = new URL(location.href).searchParams.get('session');
const track = document.getElementById('tabs');
const status = document.getElementById('status');
const subtitle = document.getElementById('subtitle');
const instructions = document.getElementById('instructions');
const position = document.getElementById('position');
const announcement = document.getElementById('announcement');
let session = null;
let closing = false;
let shortcut = 'Ctrl+Q';
let tabData = [];
let sessionPort = null;
let heartbeat = null;
let pendingControlReleaseAt = 0;
let pendingCancel = false;

function send(message) {
  return chrome.runtime.sendMessage(message).catch(() => ({ ok: false, error: 'The extension reloaded. Close this panel and try again.' }));
}

function showError(message) {
  status.textContent = message || 'Could not open recent tabs. Please try again.';
  status.hidden = false;
  track.hidden = true;
}

function domainFor(tab) {
  try {
    const url = new URL(tab.url || '');
    return url.hostname.replace(/^www\./, '') || url.protocol.replace(':', '');
  } catch { return 'Browser tab'; }
}

function initialsFor(tab) {
  const title = domainFor(tab) === 'Browser tab' ? tab.title : domainFor(tab);
  return (title || '?').replace(/^[^\p{L}\p{N}]+/u, '').slice(0, 1).toUpperCase() || '?';
}

function siteIconFor(tab) {
  const icon = element('span', 'site-icon', initialsFor(tab));
  try {
    const page = new URL(tab.url);
    if (!['https:', 'http:'].includes(page.protocol)) return icon;
    const favicon = new URL(chrome.runtime.getURL('_favicon/'));
    favicon.searchParams.set('pageUrl', page.href);
    favicon.searchParams.set('size', '32');
    const img = element('img');
    img.alt = '';
    img.addEventListener('load', () => icon.replaceChildren(img), { once: true });
    img.src = favicon.href;
  } catch { /* Keep the local initial for unsupported URLs. */ }
  return icon;
}

function element(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function addHint(key, label) {
  const hint = element('span', 'hint');
  hint.append(element('kbd', '', key), document.createTextNode(label));
  instructions.append(hint);
}

function updateInstructions() {
  instructions.replaceChildren();
  if (session?.mode === 'hold') {
    addHint(shortcut, 'cycle');
    addHint('Release Ctrl', 'switch');
    if (surface === 'popup') addHint('Enter', 'switch');
  } else {
    addHint('← →', 'choose');
    addHint('Enter', 'switch');
  }
  addHint('Esc', 'cancel');
}

function render(nextSession, tabs) {
  if (!nextSession || closing) return;
  if (requestedSessionId && nextSession.id !== requestedSessionId) return;
  session = nextSession;
  if (!sessionPort) {
    sessionPort = chrome.runtime.connect({ name: 'switcher:' + session.id });
    sessionPort.onDisconnect.addListener(() => {
      clearInterval(heartbeat);
      sessionPort = null;
      if (!closing) closePanel();
    });
    heartbeat = setInterval(() => {
      try { sessionPort?.postMessage({ type: 'alive' }); } catch { clearInterval(heartbeat); }
    }, 15000);
  }
  tabData = Array.isArray(tabs) ? tabs : tabData;
  const lookup = new Map(tabData.map(tab => [tab.id, tab]));
  const ordered = (session.selection?.ids || []).map(id => lookup.get(id)).filter(Boolean);
  document.documentElement.style.setProperty('--panel-width', `${Math.max(560, Math.min(6, ordered.length) * 203 + 43)}px`);
  const selectedId = session.selection?.ids?.[session.selection.index];
  track.replaceChildren();
  for (const [index, tab] of ordered.entries()) {
    const card = element('button', 'tab-card');
    card.type = 'button';
    card.id = `tab-${tab.id}`;
    card.setAttribute('role', 'option');
    card.setAttribute('aria-selected', String(tab.id === selectedId));
    card.setAttribute('aria-label', `${tab.title || 'Untitled tab'}, ${domainFor(tab)}`);
    card.tabIndex = -1;
    card.title = tab.title || 'Untitled tab';
    const hue = [...domainFor(tab)].reduce((hash, char) => (hash * 31 + char.charCodeAt(0)) % 360, 0);
    card.style.setProperty('--hue', String(hue));
    const thumb = element('div', 'thumbnail');
    const fallback = element('div', 'thumbnail-fallback');
    fallback.append(element('span', 'large-initial', initialsFor(tab)), element('span', 'preview-label', 'No saved preview yet'));
    if (typeof tab.thumbnail === 'string' && /^data:image\/(?:png|jpeg|webp);base64,/i.test(tab.thumbnail)) {
      const img = element('img');
      img.alt = '';
      img.src = tab.thumbnail;
      img.addEventListener('error', () => img.replaceWith(fallback), { once: true });
      thumb.append(img);
    } else thumb.append(fallback);
    thumb.append(element('span', 'card-order', String(index + 1)), element('span', 'selected-indicator', '✓'));
    const meta = element('div', 'tab-meta');
    const copy = element('div', 'tab-copy');
    copy.append(element('div', 'tab-title', tab.title || 'Untitled tab'), element('div', 'tab-domain', domainFor(tab)));
    meta.append(siteIconFor(tab), copy);
    card.append(thumb, meta);
    card.addEventListener('click', () => act('commit', { tabId: tab.id }));
    track.append(card);
  }
  if (!ordered.length) {
    showError('No recent tabs in this window yet. Visit another tab, then come back.');
  } else {
    status.hidden = true;
    track.hidden = false;
    const selected = document.getElementById(`tab-${selectedId}`);
    if (selected) {
      track.setAttribute('aria-activedescendant', selected.id);
      selected.scrollIntoView({ block: 'nearest', inline: 'center', behavior: 'instant' });
      announcement.textContent = `${lookup.get(selectedId)?.title || 'Untitled tab'}, ${session.selection.index + 1} of ${ordered.length}`;
    }
  }
  subtitle.textContent = session.mode === 'hold' ? 'Keep Control held to travel through recent tabs.' : 'Choose a tab to continue where you left off.';
  position.textContent = ordered.length ? `${Math.min((session.selection?.index || 0) + 1, ordered.length)} / ${ordered.length}` : '';
  updateInstructions();
}

async function act(type, extras = {}) {
  if (closing) return;
  if (!session) {
    if (type === 'cancel') {
      if (requestedSessionId) send({ type: 'cancel', sessionId: requestedSessionId });
      else {
        // A popup has no session token until ui-ready returns. Keep this tiny
        // startup window alive long enough to cancel that newly identified
        // session instead of leaving it active behind a closed popup.
        pendingCancel = true;
        return;
      }
      closePanel();
    }
    return;
  }
  const response = await send({ type, sessionId: session.id, ...extras });
  if (response?.session) render(response.session, response.tabs);
  if (response?.ok === false && type !== 'cancel') {
    if (!response.session) showError(response.error);
    return;
  }
  if (type === 'commit' || type === 'cancel') closePanel();
}

function closePanel() {
  if (closing) return;
  closing = true;
  clearInterval(heartbeat);
  sessionPort?.disconnect();
  sessionPort = null;
  if (surface === 'popup') window.close();
  else {
    // Only a session identifier crosses the iframe boundary; tab data never does.
    parent.postMessage({ type: 'arc-recent-tabs:close', sessionId: session?.id || requestedSessionId }, '*');
    document.body.style.display = 'none';
  }
}

document.getElementById('close').addEventListener('click', () => act('cancel'));
document.getElementById('settings').addEventListener('click', () => {
  chrome.runtime.openOptionsPage();
  act('cancel');
});
document.body.addEventListener('click', event => {
  if (surface === 'overlay' && event.target === document.body) act('cancel');
});
document.addEventListener('keydown', event => {
  if (!event.isTrusted) return;
  // Ctrl+Q belongs to chrome.commands. Handling it here would double-step.
  if (event.ctrlKey && event.key.toLowerCase() === 'q') return;
  const forward = event.key === 'ArrowRight' || event.key === 'ArrowDown' || (event.key === 'Tab' && !event.shiftKey);
  const backward = event.key === 'ArrowLeft' || event.key === 'ArrowUp' || (event.key === 'Tab' && event.shiftKey);
  if (forward || backward || event.key === 'Enter' || event.key === 'Escape') {
    event.preventDefault();
    event.stopPropagation();
    if (forward || backward) act('step', { direction: forward ? 1 : -1 });
    else act(event.key === 'Enter' ? 'commit' : 'cancel');
  }
});
document.addEventListener('keyup', event => {
  if (closing || !event.isTrusted) return;
  if (event.key === 'Control' && !event.ctrlKey) {
    // The controller owns the release commit. Sending a separate commit here
    // races that command and used to submit the same selection twice.
    const releasedAt = Date.now();
    const releaseSessionId = session?.id || requestedSessionId;
    if (!releaseSessionId) pendingControlReleaseAt = releasedAt;
    else if (session?.mode !== 'manual')
      send({ type: 'modifier-released', at: releasedAt, sessionId: releaseSessionId });
  }
});
window.addEventListener('blur', () => {
  // An outside click or changing apps must not unexpectedly switch tabs.
  if (!closing) act('cancel');
});
window.addEventListener('pagehide', () => {
  clearInterval(heartbeat);
  if (session) send({ type: 'ui-disconnected', sessionId: session.id });
  sessionPort?.disconnect();
});
chrome.runtime.onMessage.addListener(message => {
  // Broadcasts contain only a session identifier. Fetch tab data through the
  // worker's sender validation, including for web-accessible iframe documents.
  const expectedId = session?.id || requestedSessionId;
  if (message.type === 'render' && expectedId && message.sessionId === expectedId && !closing) {
    void refreshSession(expectedId);
  }
  if (message.type === 'close' && (!message.sessionId || message.sessionId === (session?.id || requestedSessionId))) closePanel();
});

async function refreshSession(sessionId) {
  const response = await send({ type: 'ui-ready', sessionId, surface });
  if (closing) return;
  if (response?.ok === false) showError(response.error);
  else {
    shortcut = response.shortcut || shortcut;
    render(response.session, response.tabs);
  }
}

async function initialize() {
  const response = await send({ type: 'ui-ready', sessionId: requestedSessionId, surface });
  if (pendingCancel) {
    if (response?.session?.id) await send({ type: 'cancel', sessionId: response.session.id });
    closePanel();
    return;
  }
  if (closing) return;
  if (response?.ok === false) showError(response.error);
  else {
    shortcut = response.shortcut || shortcut;
    render(response.session, response.tabs);
    if (!closing && session) track.focus({ preventScroll: true });
    if (pendingControlReleaseAt && session?.mode === 'hold')
      send({ type: 'modifier-released', at: pendingControlReleaseAt, sessionId: session.id });
    pendingControlReleaseAt = 0;
  }
}

// The parent document deliberately retains focus until this point. This is
// registered before initialization so a fast Control release can be buffered
// with the requested session ID even while ui-ready is still in flight.
if (surface === 'overlay' && requestedSessionId) {
  parent.postMessage({ type: 'arc-recent-tabs:keyboard-ready', sessionId: requestedSessionId }, '*');
}
void initialize();
