// Generated by GPT-6, 2026-09-08. Real Chromium smoke tests; production stays untouched.
// Usage: PLAYWRIGHT_PATH=/path/to/playwright CHROME_PATH=/path/to/chrome node tests/browser-smoke.mjs
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtemp, mkdir, cp, readFile, writeFile, appendFile, rm } from 'node:fs/promises';
import { tmpdir, homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const playwrightPath = process.env.PLAYWRIGHT_PATH || join(homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const executablePath = process.env.CHROME_PATH || join(homedir(), 'Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const { chromium } = require(playwrightPath);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const scratch = await mkdtemp(join(tmpdir(), 'recent-tabs-browser-'));
const artifacts = process.env.ARTIFACT_DIR ? resolve(process.env.ARTIFACT_DIR) : await mkdtemp(join(tmpdir(), 'recent-tabs-artifacts-'));
await mkdir(artifacts, { recursive: true });
const extension = join(scratch, 'extension');
const proofs = [];
const errors = [];
const logs = [];
let context;
let server;

const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(check, label, timeout = 5000) {
  const started = Date.now();
  let last;
  while (Date.now() - started < timeout) {
    last = await check();
    if (last) return last;
    await delay(70);
  }
  throw new Error(`Timed out waiting for ${label}; last value: ${JSON.stringify(last)}`);
}
function record(message) { proofs.push(message); process.stdout.write(`PASS ${message}\n`); }
function listen(page) {
  page.on('pageerror', error => errors.push({ page: page.url(), message: error.message }));
  page.on('console', message => {
    if (message.type() === 'error') logs.push({ page: page.url(), message: message.text() });
  });
}

try {
  await cp(join(root, 'extension'), extension, { recursive: true });
  const manifestPath = join(extension, 'manifest.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  // Permission prompts are covered manually. The throwaway fixture grants the
  // production optional permission so image/overlay behavior is deterministic.
  manifest.host_permissions = ['<all_urls>'];
  delete manifest.optional_host_permissions;
  await writeFile(manifestPath, JSON.stringify(manifest, null, 2));
  await appendFile(join(extension, 'background.js'), '\n// Test fixture only.\nglobalThis.__testController = controller;\n');
  server = createServer((request, response) => {
    const name = request.url?.slice(1, 2).toUpperCase() || 'A';
    const colors = { A: '#5b4cf4', B: '#007d76', C: '#b83961', D: '#a35911' };
    response.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' });
    response.end(`<!doctype html><html><head><title>Tab ${name}</title></head><body style="margin:0;background:${colors[name] || '#344'};color:white;font:28px system-ui;padding:70px"><h1>Tab ${name}</h1><p>Recent Tabs browser fixture</p><p>Locally rendered preview ${name}</p><input aria-label="Focus target" placeholder="Type here"></body></html>`);
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  context = await chromium.launchPersistentContext(join(scratch, 'profile'), {
    executablePath, headless: true, viewport: { width: 1440, height: 1000 },
    ignoreDefaultArgs: ['--disable-extensions'],
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
  });
  context.setDefaultTimeout(5000);
  context.on('page', listen);
  for (const page of context.pages()) listen(page);
  const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker', { timeout: 5000 });
  worker.on('console', message => { if (message.type() === 'error') logs.push({ page: worker.url(), message: message.text() }); });
  const extensionId = new URL(worker.url()).host;
  await worker.evaluate(async () => {
    await __testController.ready;
    return __testController.enqueue(() => __testController.message({ type: 'set-previews', enabled: true },
      { id: chrome.runtime.id, url: chrome.runtime.getURL('options.html') }));
  });

  const pages = {};
  const ids = {};
  for (const name of ['A', 'B', 'C', 'D']) {
    const page = pages[name] = await context.newPage();
    await page.goto(`${base}/${name}`);
    await page.bringToFront();
    ids[name] = await worker.evaluate(async url => (await chrome.tabs.query({ url }))[0].id, `${base}/${name}`);
    await until(() => worker.evaluate(id => Boolean(__testController.cache[id]), ids[name]), `saved screenshot for ${name}`);
  }
  // Remove startup blank/options tabs, leaving only the four documented fixtures.
  await worker.evaluate(async keep => {
    const tabs = await chrome.tabs.query({});
    await chrome.tabs.remove(tabs.filter(tab => !keep.includes(tab.id)).map(tab => tab.id));
  }, Object.values(ids));
  await pages.D.bringToFront();
  const session = () => worker.evaluate(() => structuredClone(__testController.session));
  const active = () => worker.evaluate(async () => (await chrome.tabs.query({ active: true, lastFocusedWindow: true }))[0]?.id);
  const begin = (direction = 1) => worker.evaluate(direction => __testController.enqueue(() => __testController.begin(direction, false)), direction);
  const frameFor = async page => until(async () => {
    const frame = page.frames().find(frame => frame.url().startsWith(`chrome-extension://${extensionId}/panel.html?session=`));
    return frame && await frame.locator('.tab-card').count() > 0 ? frame : null;
  }, 'populated preview iframe');
  const selectedTitle = frame => frame.locator('.tab-card[aria-selected="true"] .tab-title').textContent();
  const expectTitle = (frame, title) => until(async () => (await selectedTitle(frame)) === title, `selected ${title}`);
  record('Captured four actual visible-page JPEG thumbnails in session storage');

  await pages.D.keyboard.down('Control');
  await begin();
  let frame = await frameFor(pages.D);
  await expectTitle(frame, 'Tab C');
  assert.equal(await frame.locator('.thumbnail img').count(), 4);
  const original = await session();
  assert.deepEqual(original.selection.ids, [ids.D, ids.C, ids.B, ids.A]);

  // A normal webpage cannot manufacture a Control release for the isolated script.
  await pages.D.evaluate(() => document.dispatchEvent(new KeyboardEvent('keyup', { key: 'Control', ctrlKey: false, bubbles: true })));
  assert.equal((await session()).id, original.id);
  assert.equal(await active(), ids.D);
  record('Synthetic webpage Control release is ignored');

  // Give another tab even the correct nonce: sender.tab validation must reject it.
  await pages.B.evaluate(url => {
    const frame = document.createElement('iframe'); frame.id = 'spoof-panel'; frame.src = url; document.body.append(frame);
  }, `chrome-extension://${extensionId}/panel.html?session=${original.id}`);
  const attackerFrame = await until(() => pages.B.frames().find(frame => frame.url().includes(`/panel.html?session=${original.id}`)), 'other-tab extension frame');
  const refused = await attackerFrame.evaluate(async id => chrome.runtime.sendMessage({ type: 'ui-ready', surface: 'overlay', sessionId: id }), original.id);
  assert.equal(refused.ok, false);
  assert.equal(refused.tabs, undefined);
  await pages.B.evaluate(() => document.getElementById('spoof-panel').remove());
  record('Web-accessible iframe in another tab cannot retrieve titles or screenshots');

  await begin();
  await expectTitle(frame, 'Tab B');
  await begin();
  await expectTitle(frame, 'Tab A');
  const desktopBounds = await frame.evaluate(() => {
    const track = document.getElementById('tabs').getBoundingClientRect();
    const cards = [...document.querySelectorAll('.tab-card')].map(card => {
      const bounds = card.getBoundingClientRect();
      return { left: bounds.left, right: bounds.right };
    });
    return { track: { left: track.left, right: track.right }, cards };
  });
  assert.equal(desktopBounds.cards.length, 4);
  for (const card of desktopBounds.cards) {
    assert.ok(card.left >= desktopBounds.track.left - 1 && card.right <= desktopBounds.track.right + 1,
      `all four preview cards must fit within the desktop track: ${JSON.stringify(desktopBounds)}`);
  }
  await pages.D.screenshot({ path: join(artifacts, 'overlay-preview.png') });
  await pages.D.setViewportSize({ width: 600, height: 900 });
  const narrowBounds = await frame.evaluate(() => {
    const panel = document.querySelector('.switcher').getBoundingClientRect();
    return { viewport: innerWidth, bodyWidth: document.body.scrollWidth,
      documentWidth: document.documentElement.scrollWidth, left: panel.left, right: panel.right };
  });
  assert.ok(narrowBounds.bodyWidth <= narrowBounds.viewport && narrowBounds.documentWidth <= narrowBounds.viewport,
    `narrow overlay must not overflow its body: ${JSON.stringify(narrowBounds)}`);
  assert.ok(narrowBounds.left >= 0 && narrowBounds.right <= narrowBounds.viewport,
    `narrow panel must fit its viewport: ${JSON.stringify(narrowBounds)}`);
  await pages.D.setViewportSize({ width: 1440, height: 1000 });
  record('All four desktop preview cards fit fully; 600px overlay has no body overflow');
  await pages.D.keyboard.up('Control');
  await until(async () => await active() === ids.A && await session() === null, 'release commits A');
  record('Repeated commands select C → B → A; trusted Control release activates A');

  await pages.A.keyboard.down('Control');
  await begin(-1);
  frame = await frameFor(pages.A);
  await expectTitle(frame, 'Tab B');
  for (const title of ['Tab C', 'Tab D', 'Tab A', 'Tab B']) { await begin(-1); await expectTitle(frame, title); }
  await pages.A.keyboard.press('Escape');
  await pages.A.keyboard.up('Control');
  await until(async () => await session() === null, 'Escape cancels');
  assert.equal(await active(), ids.A);
  record('Reverse command wraps B → C → D → A → B; Escape preserves active tab');

  await pages.A.keyboard.down('Control');
  await begin();
  frame = await frameFor(pages.A);
  await expectTitle(frame, 'Tab D');
  await pages.D.close();
  await expectTitle(frame, 'Tab C');
  await pages.A.keyboard.press('ArrowRight');
  await expectTitle(frame, 'Tab B');
  await pages.A.keyboard.press('Enter');
  await pages.A.keyboard.up('Control');
  await until(async () => await active() === ids.B && await session() === null, 'Enter commits B');
  record('Closing selected tab picks its successor; ArrowRight and Enter work in preview');

  const restricted = await context.newPage();
  await restricted.goto('chrome://settings/');
  await restricted.bringToFront();
  await begin();
  await until(async () => (await session())?.surface === 'popup', 'restricted-page popup fallback');
  const popupContexts = () => worker.evaluate(() => chrome.runtime.getContexts({ contextTypes: ['POPUP'] }));
  const browserCDP = await context.browser().newBrowserCDPSession();
  const dismissPopup = async () => {
    const { targetInfos } = await browserCDP.send('Target.getTargets');
    const target = targetInfos.find(target => target.url === `chrome-extension://${extensionId}/popup.html`);
    assert.ok(target, 'Chrome exposes the actual action popup target');
    await browserCDP.send('Target.closeTarget', { targetId: target.targetId });
    await until(async () => (await popupContexts()).length === 0 && await session() === null, 'dismissal tears down popup session');
  };
  await until(async () => (await popupContexts()).length > 0, 'actual action popup context');
  record('chrome://settings opens an actual Chrome action popup fallback');
  // Close the actual browser popup target, exercising UI disconnect cancellation.
  await dismissPopup();
  await worker.evaluate(() => chrome.action.openPopup());
  await until(async () => (await session())?.mode === 'manual', 'toolbar action opens manual popup');
  await until(async () => (await popupContexts()).length > 0, 'manual popup context');
  await dismissPopup();
  await worker.evaluate(() => chrome.action.openPopup());
  await until(async () => (await session())?.mode === 'manual', 'manual popup reopens');
  record('Toolbar action opens a manual popup; actual target dismissal cancels the session and it reopens');

  await worker.evaluate(() => __testController.enqueue(() => __testController.cancel()));
  assert.deepEqual(errors, [], 'no unexpected browser page errors');
  record('No unexpected page errors during the browser run');
  const report = { passed: true, browserVersion: context.browser()?.version(), extensionId, proofs,
    errors, consoleErrors: logs, artifacts, nativeCommandDispatch: 'Not simulated: worker invokes the same queued command handler; modifier release and UI keys are real browser input.' };
  await writeFile(join(artifacts, 'browser-smoke.json'), JSON.stringify(report, null, 2));
  process.stdout.write(`Artifacts: ${artifacts}\n`);
} catch (error) {
  await writeFile(join(artifacts, 'browser-smoke.json'), JSON.stringify({ passed: false, proofs, errors, consoleErrors: logs, error: error.stack }, null, 2));
  process.stderr.write(`${error.stack}\nArtifacts: ${artifacts}\n`);
  process.exitCode = 1;
} finally {
  await context?.close();
  if (server) await new Promise(resolve => server.close(resolve));
  await rm(scratch, { recursive: true, force: true });
}
