// Generated by GPT-6, 2026-09-08. Integration behavior with an in-memory Chrome API.
import test from 'node:test';
import assert from 'node:assert/strict';
import { Controller } from '../extension/controller.js';
import { selectedId } from '../extension/history.js';

const clone = value => structuredClone(value);
const jpeg = 'data:image/jpeg;base64,AAAA';
const fixtureTabs = () => [
  { id: 1, windowId: 10, title: 'A private title', url: 'https://a.test/', lastAccessed: 10 },
  { id: 2, windowId: 10, title: 'B private title', url: 'https://b.test/', lastAccessed: 20 },
  { id: 3, windowId: 10, title: 'C private title', url: 'https://c.test/', lastAccessed: 30 },
  { id: 4, windowId: 10, title: 'D private title', url: 'https://d.test/', lastAccessed: 40, active: true },
  { id: 8, windowId: 20, title: 'Other window', url: 'https://e.test/', active: true },
].map(tab => ({ status: 'complete', active: false, incognito: false, discarded: false, ...tab }));

function mockChrome({ session = {}, local = {}, permission = false, tabs = fixtureTabs() } = {}) {
  const state = { session: clone(session), local: clone(local), permission, tabs: clone(tabs),
    scripts: [], notifications: [], tabMessages: [], updates: [], captures: [], popupCalls: [],
    executeScripts: [], lastFocusedWindow: 10, overlayResponse: { ok: true } };
  const storage = key => ({
    async get(keys) {
      const wanted = Array.isArray(keys) ? keys : [keys];
      return clone(Object.fromEntries(wanted.filter(keyName => keyName in state[key]).map(keyName => [keyName, state[key][keyName]])));
    },
    async set(values) { Object.assign(state[key], clone(values)); },
  });
  const api = {
    runtime: { id: 'test-extension', getURL: path => `chrome-extension://test-extension/${path}`,
      async sendMessage(message) { state.notifications.push(clone(message)); } },
    storage: { session: storage('session'), local: storage('local') },
    permissions: { async contains() { return state.permission; } },
    scripting: {
      async getRegisteredContentScripts() { return clone(state.scripts); },
      async registerContentScripts(scripts) { state.scripts.push(...clone(scripts)); },
      async unregisterContentScripts({ ids }) { state.scripts = state.scripts.filter(script => !ids.includes(script.id)); },
      async executeScript(details) { state.executeScripts.push(clone(details)); return []; },
    },
    commands: { async getAll() { return [{ name: 'next-recent', shortcut: 'Ctrl+Q' }]; } },
    action: { async openPopup(details) { state.popupCalls.push(clone(details)); } },
    windows: { async get(id) { return { id, type: 'normal', focused: id === state.lastFocusedWindow }; } },
    tabs: {
      async query(query) {
        return clone(state.tabs.filter(tab =>
          (query.windowId === undefined || tab.windowId === query.windowId) &&
          (!query.lastFocusedWindow || tab.windowId === state.lastFocusedWindow) &&
          (!query.active || tab.active)));
      },
      async get(id) {
        const tab = state.tabs.find(tab => tab.id === id);
        if (!tab) throw new Error('No tab');
        return clone(tab);
      },
      async update(id, changes) {
        const tab = state.tabs.find(tab => tab.id === id);
        if (!tab) throw new Error('No tab');
        if (changes.active) for (const sibling of state.tabs.filter(item => item.windowId === tab.windowId)) sibling.active = false;
        Object.assign(tab, changes);
        state.updates.push({ id, changes: clone(changes) });
        return clone(tab);
      },
      async sendMessage(id, message, options) {
        state.tabMessages.push({ id, message: clone(message), options: clone(options) });
        return clone(state.overlayResponse);
      },
      async captureVisibleTab(windowId, options) { state.captures.push({ windowId, options }); return jpeg; },
    },
  };
  return { api, state };
}

async function setup(t, options) {
  const { api, state } = mockChrome(options);
  const controller = new Controller(api);
  await controller.ready;
  t.after(() => { for (const timer of controller.captureTimers.values()) clearTimeout(timer); });
  const popup = { id: api.runtime.id, url: api.runtime.getURL('popup.html') };
  const overlay = { id: api.runtime.id, url: 'https://d.test/', tab: { id: 4 }, frameId: 0 };
  return { controller, api, state, popup, overlay };
}

test('queued repeated shortcuts traverse the original MRU snapshot before one commit', async t => {
  const { controller, state } = await setup(t);
  await Promise.all([
    controller.enqueue(() => controller.begin(1, false, { id: 4 })),
    controller.enqueue(() => controller.begin(1, false, { id: 4 })),
    controller.enqueue(() => controller.begin(1, false, { id: 4 })),
  ]);
  assert.deepEqual(controller.session.selection.ids, [4, 3, 2, 1]);
  assert.equal(selectedId(controller.session.selection), 1);
  assert.equal(state.popupCalls.length, 1);
  assert.deepEqual(state.updates, [], 'highlights do not activate tabs');
  assert.equal((await controller.commit()).ok, true);
  assert.deepEqual(state.updates, [{ id: 1, changes: { active: true } }]);
  assert.deepEqual(controller.history[10], [1, 4, 3, 2]);
  assert.equal(controller.session, null);
});

test('toolbar popup creates a manual session and ignores modifier releases', async t => {
  const { controller, popup, overlay, state } = await setup(t);
  const response = await controller.message({ type: 'ui-ready', surface: 'popup' }, popup);
  assert.equal(response.ok, true);
  assert.equal(response.session.mode, 'manual');
  assert.deepEqual(response.tabs.map(tab => tab.id), [4, 3, 2, 1]);
  assert.equal(selectedId(controller.session.selection), 3);
  await controller.message({ type: 'modifier-released', at: Date.now() + 10 }, overlay);
  assert.equal(controller.session.mode, 'manual');
  assert.deepEqual(state.updates, []);
  await controller.message({ type: 'commit', sessionId: controller.session.id, tabId: 2 }, popup);
  assert.equal(state.updates.at(-1).id, 2);
});

test('held shortcut ignores stale, wrong-tab, and subframe key releases', async t => {
  const { controller, overlay, state } = await setup(t);
  const requestedAt = Date.now();
  await controller.begin(1, false, { id: 4 }, requestedAt);
  await controller.message({ type: 'modifier-released', at: requestedAt - 1 }, overlay);
  await controller.message({ type: 'modifier-released', at: requestedAt + 1 }, { ...overlay, tab: { id: 2 } });
  await controller.message({ type: 'modifier-released', at: requestedAt + 1 }, { ...overlay, frameId: 9 });
  assert.equal(controller.session.mode, 'hold');
  assert.deepEqual(state.updates, []);
  await controller.message({ type: 'modifier-released', at: requestedAt + 1 }, overlay);
  assert.equal(controller.session, null);
  assert.equal(state.updates.at(-1).id, 3);
});

test('untrusted or stale UI cannot retrieve titles or cached screenshots', async t => {
  const { controller, popup, overlay, api } = await setup(t);
  await controller.begin(1, true);
  for (const sender of [
    overlay,
    { ...popup, id: 'different-extension' },
    { ...popup, url: api.runtime.getURL('popup.html.evil') },
    { ...popup, tab: { id: 99 } },
    { id: api.runtime.id, url: 'https://attacker.test/popup.html' },
  ]) {
    const response = await controller.message({ type: 'ui-ready', surface: 'popup', sessionId: controller.session.id }, sender);
    assert.equal(response.ok, false);
    assert.equal(response.tabs, undefined);
    assert.equal(JSON.stringify(response).includes('private title'), false);
  }
  assert.equal((await controller.message({ type: 'ui-ready', sessionId: 'stale' }, popup)).ok, false);
  assert.equal((await controller.message({ type: 'ui-ready', sessionId: controller.session.id }, popup)).ok, true);
});

test('web-accessible panel needs an overlay session token and cannot impersonate toolbar popup', async t => {
  const { controller, api } = await setup(t);
  const panel = { id: api.runtime.id, url: api.runtime.getURL('panel.html'), tab: { id: 4 }, frameId: 2 };
  assert.equal((await controller.message({ type: 'ui-ready', surface: 'popup' }, panel)).ok, false);
  assert.equal(controller.session, null);
  await controller.begin(1, true);
  assert.equal((await controller.message({ type: 'ui-ready', surface: 'overlay' }, panel)).ok, false);
  const authorized = await controller.message({ type: 'ui-ready', surface: 'overlay', sessionId: controller.session.id }, panel);
  assert.equal(authorized.ok, true);
  assert.equal(authorized.tabs.length, 4);
});

test('arbitrary tab IDs and stale session commands cannot activate tabs', async t => {
  const { controller, popup, state } = await setup(t);
  await controller.begin(1, true);
  assert.equal((await controller.message({ type: 'commit', sessionId: controller.session.id, tabId: 8 }, popup)).ok, false);
  assert.equal((await controller.message({ type: 'commit', sessionId: 'old', tabId: 3 }, popup)).ok, false);
  assert.deepEqual(state.updates, []);
  assert.ok(controller.session);
});

test('closing or moving highlighted tab prevents activation and selects successor', async t => {
  const { controller, state } = await setup(t);
  await controller.begin(1, true);
  state.tabs.find(tab => tab.id === 3).windowId = 20;
  assert.equal((await controller.commit()).ok, false);
  assert.equal(selectedId(controller.session.selection), 2);
  state.tabs = state.tabs.filter(tab => tab.id !== 2);
  assert.equal((await controller.commit()).ok, false);
  assert.equal(selectedId(controller.session.selection), 1);
  assert.deepEqual(state.updates, []);
  await controller.commit();
  assert.equal(state.updates.at(-1).id, 1);
});

test('source removal cancels session and sends close/hide notifications', async t => {
  const { controller, state } = await setup(t);
  await controller.begin(1, true);
  const sessionId = controller.session.id;
  await controller.removed(4);
  assert.equal(controller.session, null);
  assert.equal(state.session.selectionSession, null);
  assert.ok(state.notifications.some(message => message.type === 'close' && message.sessionId === sessionId));
  assert.ok(state.tabMessages.some(({ message }) => message.type === 'hide-overlay' && message.sessionId === sessionId));
});

test('navigation invalidates screenshot immediately and cancels source overlay', async t => {
  const { controller, state } = await setup(t, { permission: true, local: { previewsEnabled: true },
    session: { previewCache: { 4: { data: jpeg, url: 'https://d.test/', at: 1 } } } });
  await controller.begin(1, true);
  await controller.updated(4, { status: 'loading' }, { id: 4, active: true, url: 'https://d.test/' });
  assert.equal(controller.cache[4], undefined);
  assert.equal(state.session.previewCache[4], undefined);
  assert.equal(controller.navigationVersions.get(4), 1);
  assert.equal(controller.session, null);
});

test('preview permission toggles clear cache, sync scripts, and gate thumbnails', async t => {
  const { controller, state, popup } = await setup(t);
  assert.deepEqual(await controller.message({ type: 'set-previews', enabled: true }, popup), { ok: true, enabled: false });
  assert.equal(state.scripts.length, 0);
  state.permission = true;
  assert.equal((await controller.message({ type: 'set-previews', enabled: true }, popup)).enabled, true);
  assert.equal(state.scripts[0].id, 'arc-overlay');
  assert.equal(state.executeScripts.length, 5);
  controller.cache[3] = { data: jpeg, url: 'https://c.test/', at: 1 };
  controller.cache[2] = { data: jpeg, url: 'https://old-location.test/', at: 1 };
  const payload = await controller.begin(1, true);
  assert.equal(payload.tabs.find(tab => tab.id === 3).thumbnail, jpeg);
  assert.equal(payload.tabs.find(tab => tab.id === 2).thumbnail, undefined);
  await controller.message({ type: 'set-previews', enabled: false }, popup);
  assert.equal(controller.session, null);
  assert.deepEqual(controller.cache, {});
  assert.deepEqual(state.session.previewCache, {});
  assert.equal(state.local.previewsEnabled, false);
  assert.equal(state.scripts.length, 0);
});

test('worker restart restores MRU/cache while abandoning any previous UI selection', async t => {
  const selectionSession = { id: 'saved-session', windowId: 10, sourceTabId: 4, mode: 'hold',
    selection: { ids: [4, 3, 2, 1], index: 2 }, createdAt: Date.now() - 100, surface: 'popup' };
  const { controller, state } = await setup(t, { permission: true, local: { previewsEnabled: true }, session: {
    history: { 10: [4, 1, 3, 2] }, selectionSession,
    previewCache: { 3: { data: jpeg, url: 'https://c.test/', at: 1 },
      2: { data: jpeg, url: 'https://wrong.test/', at: 2 }, 99: { data: jpeg, url: 'https://gone.test/', at: 3 } },
  } });
  assert.equal(controller.session, null);
  assert.equal(state.session.selectionSession, null);
  assert.deepEqual(controller.history[10], [4, 1, 3, 2]);
  assert.deepEqual(Object.keys(controller.cache), ['3']);
});

test('worker restart deletes previously cached screenshots when permission was removed', async t => {
  const { controller, state } = await setup(t, { local: { previewsEnabled: true }, permission: false,
    session: { previewCache: { 3: { data: jpeg, url: 'https://c.test/', at: 1 } } } });
  assert.equal(controller.enabled, false);
  assert.deepEqual(controller.cache, {});
  assert.deepEqual(state.session.previewCache, {});
});

test('render notifications never broadcast tab metadata or preview images', async t => {
  const { controller, state } = await setup(t);
  await controller.begin(1, true);
  await controller.render();
  const message = state.notifications.find(item => item.type === 'render');
  assert.deepEqual(message, { type: 'render', sessionId: controller.session.id });
  assert.equal(JSON.stringify(state.notifications).includes('private title'), false);
});

test('worker restart drops stale sessions and sessions whose source is inactive', async t => {
  const previous = { id: 'saved', windowId: 10, sourceTabId: 4,
    selection: { ids: [4, 3], index: 1 }, mode: 'hold', createdAt: Date.now() - 301_000 };
  const stale = await setup(t, { session: { selectionSession: previous } });
  assert.equal(stale.controller.session, null);
  const inactive = await setup(t, { session: { selectionSession: { ...previous, sourceTabId: 3, createdAt: Date.now() } } });
  assert.equal(inactive.controller.session, null);
});

test('overlay release observed during injection commits the first selection', async t => {
  const { controller, state } = await setup(t, { permission: true, local: { previewsEnabled: true } });
  const requestedAt = Date.now();
  state.overlayResponse = { ok: true, releasedAt: requestedAt + 1 };
  await controller.enqueue(() => controller.begin(1, false, { id: 4 }, requestedAt));
  assert.equal(state.popupCalls.length, 0);
  assert.equal(controller.session, null);
  assert.equal(state.updates.at(-1).id, 3);
});

test('overlay failure falls back to popup; popup failure leaves no stranded session', async t => {
  const { controller, state, api } = await setup(t, { permission: true, local: { previewsEnabled: true } });
  state.overlayResponse = { ok: false };
  await controller.begin();
  assert.equal(state.popupCalls.length, 1);
  assert.equal(controller.session.surface, 'popup');
  await controller.cancel();
  api.action.openPopup = async () => { throw new Error('cannot open'); };
  await assert.rejects(controller.begin(), /Pin the extension/);
  assert.equal(controller.session, null);
});

test('queue resumes after a rejected operation and never poisons later requests', async t => {
  const { controller } = await setup(t);
  t.mock.method(console, 'warn', () => {});
  await assert.rejects(controller.enqueue(() => { throw new Error('first failed'); }), /first failed/);
  await controller.enqueue(() => controller.begin(1, true));
  assert.equal(selectedId(controller.session.selection), 3);
});

function mockImageRuntime(t, onDecode = async () => {}) {
  const previousBitmap = globalThis.createImageBitmap;
  const previousCanvas = globalThis.OffscreenCanvas;
  t.mock.method(globalThis, 'fetch', async () => ({ blob: async () => 'blob' }));
  globalThis.createImageBitmap = async () => {
    await onDecode();
    return { width: 1200, height: 800, close() {} };
  };
  globalThis.OffscreenCanvas = class {
    getContext() { return { drawImage() {} }; }
    async convertToBlob() { return { arrayBuffer: async () => Uint8Array.from([255, 216, 255]).buffer }; }
  };
  t.after(() => {
    if (previousBitmap === undefined) delete globalThis.createImageBitmap;
    else globalThis.createImageBitmap = previousBitmap;
    if (previousCanvas === undefined) delete globalThis.OffscreenCanvas;
    else globalThis.OffscreenCanvas = previousCanvas;
  });
}

test('completed screenshot capture saves only a focused active eligible tab', async t => {
  const { controller, state } = await setup(t, { permission: true, local: { previewsEnabled: true } });
  mockImageRuntime(t);
  await controller.capture(1);
  await controller.capture(8);
  assert.equal(state.captures.length, 0, 'inactive tab and background window are excluded');
  await controller.capture(4);
  assert.equal(state.captures.length, 1);
  assert.equal(controller.cache[4].url, 'https://d.test/');
  assert.equal(controller.cache[4].data, 'data:image/jpeg;base64,/9j/');
  assert.deepEqual(state.session.previewCache, controller.cache);
  assert.equal(controller.captureBusy, false);
});

test('navigation during image processing discards the stale screenshot', async t => {
  const { controller, state } = await setup(t, { permission: true, local: { previewsEnabled: true } });
  let decoding;
  const decodeStarted = new Promise(resolve => { decoding = resolve; });
  let finish;
  const decodeGate = new Promise(resolve => { finish = resolve; });
  mockImageRuntime(t, async () => { decoding(); await decodeGate; });
  const capturing = controller.capture(4);
  await decodeStarted;
  state.tabs.find(tab => tab.id === 4).url = 'https://new-d.test/';
  await controller.updated(4, { status: 'loading' }, { id: 4, active: true, url: 'https://new-d.test/' });
  finish();
  await capturing;
  assert.deepEqual(controller.cache, {});
  assert.equal(controller.captureBusy, false);
});

test('clearing previews during image processing cannot repopulate cleared cache', async t => {
  const { controller, popup } = await setup(t, { permission: true, local: { previewsEnabled: true } });
  let decoding;
  const decodeStarted = new Promise(resolve => { decoding = resolve; });
  let finish;
  const decodeGate = new Promise(resolve => { finish = resolve; });
  mockImageRuntime(t, async () => { decoding(); await decodeGate; });
  const capturing = controller.capture(4);
  await decodeStarted;
  await controller.message({ type: 'clear-previews' }, popup);
  finish();
  await capturing;
  assert.deepEqual(controller.cache, {});
  assert.equal(controller.captureBusy, false);
});

test('an activation event invalidates an in-flight screenshot even when original tab becomes active again', async t => {
  const { controller } = await setup(t, { permission: true, local: { previewsEnabled: true } });
  let decoding;
  const decodeStarted = new Promise(resolve => { decoding = resolve; });
  let finish;
  const decodeGate = new Promise(resolve => { finish = resolve; });
  mockImageRuntime(t, async () => { decoding(); await decodeGate; });
  const capturing = controller.capture(4);
  await decodeStarted;
  // background.js increments this immediately at the Chrome event boundary,
  // before queued activation handlers or a screenshot save can run.
  controller.captureGeneration++;
  await controller.activated({ tabId: 3, windowId: 10 });
  controller.captureGeneration++;
  await controller.activated({ tabId: 4, windowId: 10 });
  finish();
  await capturing;
  assert.deepEqual(controller.cache, {});
});
