// Generated by GPT-6, 2026-09-08. Behavioral tests for tab navigation history.
import test from 'node:test';
import assert from 'node:assert/strict';
import {
  reconcileHistory, recordActivation, removeTab, createSelection,
  stepSelection, removeFromSelection, selectedId,
} from '../extension/history.js';

test('A B C D visit order traverses every prior tab without ping-pong', () => {
  let history = {};
  for (const id of [1, 2, 3, 4]) history = recordActivation(history, 10, id);
  assert.deepEqual(history, { 10: [4, 3, 2, 1] });
  let selection = createSelection(history[10]);
  const highlights = [selectedId(selection)];
  for (let i = 0; i < 3; i++) {
    // Even if an integration records highlights, the gesture stays frozen.
    history = recordActivation(history, 10, selectedId(selection));
    selection = stepSelection(selection);
    highlights.push(selectedId(selection));
  }
  assert.deepEqual(highlights, [3, 2, 1, 4]);
  assert.deepEqual(selection.ids, [4, 3, 2, 1]);
});

test('forward and reverse gestures wrap predictably', () => {
  let selection = createSelection([4, 3, 2, 1], -1);
  assert.equal(selectedId(selection), 1);
  const highlights = [];
  for (let i = 0; i < 5; i++) {
    selection = stepSelection(selection, -1);
    highlights.push(selectedId(selection));
  }
  assert.deepEqual(highlights, [2, 3, 4, 1, 2]);
  assert.equal(selectedId(stepSelection(selection, 1)), 1);
});

test('a tab closed before or after selection preserves highlighted tab', () => {
  const original = stepSelection(createSelection([4, 3, 2, 1]));
  assert.equal(selectedId(original), 2);
  const before = removeFromSelection(original, 4);
  assert.deepEqual(before, { ids: [3, 2, 1], index: 1 });
  const after = removeFromSelection(original, 1);
  assert.deepEqual(after, { ids: [4, 3, 2], index: 2 });
  assert.deepEqual(original, { ids: [4, 3, 2, 1], index: 2 });
});

test('closing highlighted tab selects successor and wraps at end', () => {
  const middle = createSelection([4, 3, 2, 1]);
  assert.equal(selectedId(removeFromSelection(middle, 3)), 2);
  const end = createSelection([4, 3, 2, 1], -1);
  assert.equal(selectedId(removeFromSelection(end, 1)), 4);
  assert.equal(removeFromSelection(createSelection([4]), 4), null);
});

test('empty, singleton, missing-tab and duplicate snapshots are safe', () => {
  assert.equal(createSelection([]), null);
  assert.equal(selectedId(null), null);
  assert.equal(stepSelection(null), null);
  assert.equal(removeFromSelection(null, 1), null);
  const singleton = createSelection([8, 8, null, -1, '8']);
  assert.deepEqual(singleton, { ids: [8], index: 0 });
  assert.deepEqual(stepSelection(singleton, -1), singleton);
  assert.deepEqual(removeFromSelection(singleton, 42), singleton);
});

test('snapshot cannot be reordered accidentally or by mutating source', () => {
  const source = [4, 3, 2, 1];
  const selection = createSelection(source);
  source.reverse();
  assert.deepEqual(selection.ids, [4, 3, 2, 1]);
  assert.throws(() => selection.ids.reverse(), TypeError);
  const next = stepSelection(selection);
  assert.equal(next.ids, selection.ids);
  assert.equal(selection.index, 1);
});

test('activation de-duplicates one window and does not mutate other windows', () => {
  const original = { 10: [4, 3, 4, 2], 20: [8, 7] };
  const updated = recordActivation(original, 10, 3);
  assert.deepEqual(updated, { 10: [3, 4, 2], 20: [8, 7] });
  assert.deepEqual(original, { 10: [4, 3, 4, 2], 20: [8, 7] });
  assert.deepEqual(recordActivation(updated, 30, 9)[30], [9]);
});

test('removing tab purges every window without mutating stored histories', () => {
  const original = { 10: [3, 2, 1], 20: [8, 3, 7] };
  assert.deepEqual(removeTab(original, 3), { 10: [2, 1], 20: [8, 7] });
  assert.deepEqual(original, { 10: [3, 2, 1], 20: [8, 3, 7] });
});

test('startup uses active tab first and lastAccessed for remaining tabs', () => {
  const tabs = [
    { id: 1, windowId: 10, active: true, lastAccessed: 10 },
    { id: 2, windowId: 10, lastAccessed: 20 },
    { id: 3, windowId: 10, lastAccessed: 30 },
    { id: 8, windowId: 20, lastAccessed: 5 },
    { id: 7, windowId: 20, active: true, lastAccessed: 1 },
  ];
  assert.deepEqual(reconcileHistory({}, tabs), { 10: [1, 3, 2], 20: [7, 8] });
});

test('resync keeps saved order, appends unknown by recency, and purges stale IDs/windows', () => {
  const saved = { 10: [4, 2, 4, 99, 1, 8], 20: [7], 30: [88] };
  const tabs = [
    { id: 1, windowId: 10, active: true, lastAccessed: 1 },
    { id: 2, windowId: 10, lastAccessed: 500 },
    { id: 4, windowId: 10, lastAccessed: 100 },
    { id: 3, windowId: 10, lastAccessed: 900 },
    { id: 5, windowId: 10, lastAccessed: 800 },
    { id: 8, windowId: 20, active: true },
    { id: 7, windowId: 20 },
  ];
  assert.deepEqual(reconcileHistory(saved, tabs), { 10: [1, 4, 2, 3, 5], 20: [8, 7] });
  assert.deepEqual(saved, { 10: [4, 2, 4, 99, 1, 8], 20: [7], 30: [88] });
});

test('reconciliation tolerates duplicate and malformed tab records', () => {
  const tabs = [
    { id: 2, windowId: 10 },
    { id: 2, windowId: 10, active: true },
    { id: 3, windowId: 10 },
    { id: -1, windowId: 10 },
    { id: 4, windowId: -1 },
    null,
  ];
  assert.deepEqual(reconcileHistory({ 10: [3, 3] }, tabs), { 10: [2, 3] });
  assert.deepEqual(reconcileHistory({ 10: [1] }, []), {});
});
