// Generated by GPT-5.6 Terra and GPT-6 Astra, Codex desktop, 2026-09-08.
// Execute the shipped isolated-world and panel scripts with small DOM/Chrome
// doubles. This covers the focus handoff that browser-only tests cannot make
// deterministic without driving native Chrome keyboard state.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';

const overlaySource = await readFile(new URL('../extension/overlay.js', import.meta.url), 'utf8');
const panelSource = await readFile(new URL('../extension/panel.js', import.meta.url), 'utf8');
const extensionURL = path => `chrome-extension://test-extension/${path.replace(/^\//, '')}`;
const nextTurn = () => new Promise(resolve => setImmediate(resolve));

function eventTarget(target = {}) {
  const listeners = new Map();
  return Object.assign(target, {
    addEventListener(type, listener) {
      const entries = listeners.get(type) || [];
      entries.push(listener);
      listeners.set(type, entries);
    },
    dispatch(type, event = {}) {
      for (const listener of listeners.get(type) || []) listener(event);
    },
  });
}

function runOverlay() {
  let listener;
  const messages = [];
  const document = eventTarget({
    activeElement: { isConnected: true, focus() {} },
    hidden: false,
    documentElement: { append(node) { this.child = node; } },
    body: {},
    createElement(tag) {
      if (tag === 'iframe') {
        const iframe = eventTarget({ style: {}, contentWindow: { focus() { iframe.windowFocuses++; } },
          focus() { this.focuses++; }, focuses: 0, windowFocuses: 0 });
        this.iframe = iframe;
        return iframe;
      }
      return eventTarget({ style: {}, setAttribute() {}, remove() { this.removed = true; },
        attachShadow() { return { append(node) { this.child = node; } }; } });
    },
  });
  const window = eventTarget({ setTimeout(callback) { callback(); },
    document, hasFocus() { return true; } });
  const chrome = { runtime: {
    id: 'test-extension', getURL: extensionURL,
    sendMessage(message) { messages.push(message); return Promise.resolve(); },
    onMessage: { addListener(next) { listener = next; } },
  } };
  vm.runInNewContext(overlaySource, { chrome, document, window, URL, Date, globalThis: {},
    setTimeout: callback => callback() });
  return { chrome, document, window, messages, show(message) {
    let response;
    listener(message, { id: chrome.runtime.id }, value => { response = value; });
    return response;
  } };
}

function panelNode() {
  return eventTarget({ hidden: false, textContent: '', style: { setProperty() {} },
    replaceChildren() {}, append() {}, setAttribute() {}, focus() { this.focuses = (this.focuses || 0) + 1; } });
}

function runPanel({ response = { ok: false, error: 'closed' }, surface = 'overlay' } = {}) {
  const sent = [];
  const parentMessages = [];
  const nodes = new Map(['tabs', 'status', 'subtitle', 'instructions', 'position', 'announcement', 'close', 'settings']
    .map(id => [id, panelNode()]));
  const document = eventTarget({
    body: eventTarget({ dataset: { surface }, style: {} }),
    documentElement: { style: { setProperty() {} } },
    getElementById(id) { return nodes.get(id); },
    createElement() { return panelNode(); },
    createTextNode(text) { return { textContent: text }; },
  });
  const window = eventTarget({ closes: 0, close() { this.closes++; } });
  const parent = { postMessage(message) { parentMessages.push(message); } };
  const chrome = { runtime: {
    getURL: extensionURL,
    sendMessage(message) { sent.push(message); return Promise.resolve(response); },
    onMessage: { addListener() {} },
    connect() { return { onDisconnect: { addListener() {} }, disconnect() {}, postMessage() {} }; },
    openOptionsPage() {},
  } };
  const panelURL = extensionURL(surface === 'overlay' ? 'panel.html?session=s1' : 'popup.html');
  vm.runInNewContext(panelSource, { chrome, document, window, parent, location: { href: panelURL },
    URL, Date, setInterval: () => 1, clearInterval() {}, Promise });
  return { document, sent, parentMessages, nodes, window };
}

test('overlay keeps page focus through a fast Control release and focuses only after panel readiness', () => {
  const ui = runOverlay();
  const opened = ui.show({ type: 'show-overlay', sessionId: 's1' });
  assert.equal(opened.ok, true);
  assert.equal(opened.releasedAt, 0);
  assert.equal(opened.controlHeld, null);
  assert.equal(ui.document.iframe.focuses, 0);

  ui.document.dispatch('keyup', { isTrusted: true, key: 'Control', ctrlKey: false });
  assert.equal(ui.messages.at(-1).type, 'modifier-released');
  assert.equal(ui.messages.at(-1).sessionId, 's1');
  assert.equal(ui.document.iframe.focuses, 0);

  ui.window.dispatch('message', { source: ui.document.iframe.contentWindow,
    origin: new URL(extensionURL('/')).origin,
    data: { type: 'arc-recent-tabs:keyboard-ready', sessionId: 's1' } });
  assert.equal(ui.document.iframe.focuses, 1);
  assert.equal(ui.document.iframe.windowFocuses, 1);

  ui.show({ type: 'hide-overlay', sessionId: 's1' });
  ui.window.dispatch('message', { source: ui.document.iframe.contentWindow,
    origin: new URL(extensionURL('/')).origin,
    data: { type: 'arc-recent-tabs:keyboard-ready', sessionId: 's1' } });
  assert.equal(ui.document.iframe.focuses, 1, 'a late initialize cannot refocus a closed overlay');
});

test('panel ignores synthetic keys and sends one modifier release without a duplicate commit', async () => {
  const ui = runPanel();
  await nextTurn();
  assert.equal(ui.parentMessages.length, 1);
  assert.equal(ui.parentMessages[0].type, 'arc-recent-tabs:keyboard-ready');
  assert.equal(ui.parentMessages[0].sessionId, 's1');
  const before = ui.sent.length;
  ui.document.dispatch('keyup', { isTrusted: false, key: 'Control', ctrlKey: false });
  ui.document.dispatch('keydown', { isTrusted: false, key: 'Escape', ctrlKey: false });
  assert.equal(ui.sent.length, before, 'synthetic events cannot release, commit, or cancel');

  ui.document.dispatch('keyup', { isTrusted: true, key: 'Control', ctrlKey: false });
  const releaseMessages = ui.sent.slice(before).filter(message => message.type === 'modifier-released');
  assert.equal(releaseMessages.length, 1);
  assert.equal(ui.sent.slice(before).some(message => message.type === 'commit'), false);

  ui.document.dispatch('keyup', { isTrusted: true, key: 'Control', ctrlKey: false });
  assert.equal(ui.sent.slice(before).filter(message => message.type === 'modifier-released').length, 2,
    'each real keyup is forwarded once; the controller de-duplicates after its first commit');
});

test('popup buffers a startup release until ui-ready supplies its hold session', async () => {
  let resolve;
  const ui = runPanel({ surface: 'popup', response: new Promise(next => { resolve = next; }) });
  ui.document.dispatch('keyup', { isTrusted: true, key: 'Control', ctrlKey: false });
  assert.equal(ui.sent.filter(message => message.type === 'modifier-released').length, 0);
  resolve({ ok: true, session: { id: 's1', mode: 'hold', selection: { ids: [], index: 0 } }, tabs: [] });
  await nextTurn();
  const releases = ui.sent.filter(message => message.type === 'modifier-released');
  assert.equal(releases.length, 1);
  assert.equal(releases[0].sessionId, 's1');
  assert.equal(ui.sent.some(message => message.type === 'commit'), false);
});

test('a manual panel ignores a Control release after it initializes', async () => {
  const ui = runPanel({ surface: 'popup', response: {
    ok: true, session: { id: 's1', mode: 'manual', selection: { ids: [], index: 0 } }, tabs: [],
  } });
  await nextTurn();
  const before = ui.sent.length;
  ui.document.dispatch('keyup', { isTrusted: true, key: 'Control', ctrlKey: false });
  assert.equal(ui.sent.length, before);
});

test('a closed panel cancels its late session and never focuses after ui-ready resolves', async () => {
  let resolve;
  const ui = runPanel({ surface: 'popup', response: new Promise(next => { resolve = next; }) });
  ui.document.dispatch('keydown', { isTrusted: true, key: 'Escape', ctrlKey: false,
    preventDefault() {}, stopPropagation() {} });
  assert.equal(ui.window.closes, 0, 'the unknown popup session must remain alive until it can be cancelled');
  resolve({ ok: true, session: { id: 's1', mode: 'hold', selection: { ids: [], index: 0 } }, tabs: [] });
  await nextTurn();
  assert.equal(ui.nodes.get('tabs').focuses || 0, 0);
  assert.equal(ui.window.closes, 1);
  const cancellations = ui.sent.filter(message => message.type === 'cancel');
  assert.equal(cancellations.length, 1);
  assert.equal(cancellations[0].sessionId, 's1');
});


test('overlay focus loss during startup cancels and cannot refocus after initialization', async () => {
  let resolve;
  const ui = runPanel({ response: new Promise(next => { resolve = next; }) });
  ui.window.dispatch('blur');
  assert.equal(ui.sent.filter(message => message.type === 'cancel' && message.sessionId === 's1').length, 1);
  const messagesAfterCancel = ui.sent.length;
  ui.document.dispatch('keyup', { isTrusted: true, key: 'Control', ctrlKey: false });
  assert.equal(ui.sent.length, messagesAfterCancel, 'a closed overlay ignores release');
  resolve({ ok: true, session: { id: 's1', mode: 'hold', selection: { ids: [], index: 0 } }, tabs: [] });
  await nextTurn();
  assert.equal(ui.nodes.get('tabs').focuses || 0, 0);
});

test('a startup release never automatically selects from a manual popup', async () => {
  let resolve;
  const ui = runPanel({ surface: 'popup', response: new Promise(next => { resolve = next; }) });
  ui.document.dispatch('keyup', { isTrusted: true, key: 'Control', ctrlKey: false });
  resolve({ ok: true, session: { id: 's1', mode: 'manual', selection: { ids: [], index: 0 } }, tabs: [] });
  await nextTurn();
  assert.equal(ui.sent.some(message => message.type === 'modifier-released' || message.type === 'commit'), false);
});
