// Generated by GPT-6, 2026-09-08. Local screenshot cache and image-resize tests.
import test from 'node:test';
import assert from 'node:assert/strict';
import { trimPreviews, previewBytes, shrinkScreenshot, MAX_PREVIEW_COUNT } from '../extension/previews.js';

const image = (at, length = 20, url = 'https://example.test/') => ({
  at, url, data: 'data:image/jpeg;base64,' + 'A'.repeat(length),
});

test('preview cache evicts oldest images and rejects non-JPEG inputs', () => {
  const cache = Object.fromEntries(Array.from({ length: 35 }, (_, i) => [i, image(i)]));
  cache.invalid = { at: 999, data: 'https://remote.test/tracking.png' };
  cache.png = { at: 999, data: 'data:image/png;base64,AAAA' };
  const trimmed = trimPreviews(cache);
  assert.equal(Object.keys(trimmed).length, MAX_PREVIEW_COUNT);
  for (let i = 0; i < 5; i++) assert.equal(trimmed[i], undefined);
  for (let i = 5; i < 35; i++) assert.deepEqual(trimmed[i], cache[i]);
  assert.equal(trimmed.invalid, undefined);
  assert.equal(trimmed.png, undefined);
  assert.equal(Object.keys(cache).length, 37, 'input cache remains unchanged');
});

test('byte budget accounts for UTF-16 images, URLs, and metadata', () => {
  const newest = image(3, 20);
  const second = image(2, 20);
  const itemCost = newest.data.length * 2 + newest.url.length * 2 + 128;
  const trimmed = trimPreviews({ a: second, b: newest }, itemCost);
  assert.deepEqual(trimmed, { b: newest });
  assert.equal(previewBytes(trimmed), newest.data.length * 2);
  assert.deepEqual(trimPreviews({ a: newest }, 0), {});
  assert.deepEqual(trimPreviews({ a: newest }, 5000, 0), {});
});

test('oversized newest image does not prevent a smaller image from fitting', () => {
  const small = image(1, 1);
  assert.deepEqual(trimPreviews({ large: image(2, 5000), small }, 500), { small });
});

test('screenshot resize caps width, preserves aspect ratio, and releases bitmap', async t => {
  const calls = [];
  const bitmap = { width: 1440, height: 900, close: () => calls.push('close') };
  const source = 'data:image/jpeg;base64,AAAA';
  t.mock.method(globalThis, 'fetch', async data => {
    assert.equal(data, source);
    return { blob: async () => 'source-blob' };
  });
  const previousBitmap = globalThis.createImageBitmap;
  const previousCanvas = globalThis.OffscreenCanvas;
  globalThis.createImageBitmap = async blob => { assert.equal(blob, 'source-blob'); return bitmap; };
  globalThis.OffscreenCanvas = class {
    constructor(width, height) { calls.push(['canvas', width, height]); }
    getContext(kind) {
      assert.equal(kind, '2d');
      return { drawImage: (...args) => calls.push(['draw', ...args]) };
    }
    async convertToBlob(options) {
      calls.push(['encode', options]);
      return { arrayBuffer: async () => Uint8Array.from([255, 216, 255]).buffer };
    }
  };
  t.after(() => {
    if (previousBitmap === undefined) delete globalThis.createImageBitmap;
    else globalThis.createImageBitmap = previousBitmap;
    if (previousCanvas === undefined) delete globalThis.OffscreenCanvas;
    else globalThis.OffscreenCanvas = previousCanvas;
  });
  assert.equal(await shrinkScreenshot(source), 'data:image/jpeg;base64,/9j/');
  assert.deepEqual(calls[0], ['canvas', 480, 300]);
  assert.deepEqual(calls[1], ['draw', bitmap, 0, 0, 480, 300]);
  assert.deepEqual(calls[2], ['encode', { type: 'image/jpeg', quality: 0.62 }]);
  assert.equal(calls.at(-1), 'close');
});

test('encoding failure still closes decoded screenshot bitmap', async t => {
  let closed = false;
  const previousBitmap = globalThis.createImageBitmap;
  const previousCanvas = globalThis.OffscreenCanvas;
  t.mock.method(globalThis, 'fetch', async () => ({ blob: async () => 'blob' }));
  globalThis.createImageBitmap = async () => ({ width: 100, height: 80, close: () => { closed = true; } });
  globalThis.OffscreenCanvas = class {
    constructor(width, height) { assert.deepEqual([width, height], [100, 80]); }
    getContext() { return { drawImage() {} }; }
    async convertToBlob() { throw new Error('encoding failed'); }
  };
  t.after(() => {
    if (previousBitmap === undefined) delete globalThis.createImageBitmap;
    else globalThis.createImageBitmap = previousBitmap;
    if (previousCanvas === undefined) delete globalThis.OffscreenCanvas;
    else globalThis.OffscreenCanvas = previousCanvas;
  });
  await assert.rejects(shrinkScreenshot('data:image/jpeg;base64,AAAA'), /encoding failed/);
  assert.equal(closed, true);
});
